# Generated by Django 4.2.8 on 2023-12-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wypozyczenie',
            name='owner',
        ),
    ]
