# Generated by Django 4.2.6 on 2024-01-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0005_rename_osoba_ksiazka_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='wypozyczenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.wypozyczenie'),
        ),
    ]
